<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyFinance.Domain\MyFinance.Domain.csproj" />
    <ProjectReference Include="..\MyFinance.Infra\MyFinance.Infra.csproj" />
  </ItemGroup>

</Project>
